// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/apikey"
	"github.com/leeforge/core/server/ent/predicate"
	"github.com/leeforge/core/server/ent/role"
	"github.com/leeforge/core/server/ent/user"
)

// ApiKeyUpdate is the builder for updating ApiKey entities.
type ApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyMutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdate) Where(ps ...predicate.ApiKey) *ApiKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *ApiKeyUpdate) SetUpdatedByID(v uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableUpdatedByID(v *uuid.UUID) *ApiKeyUpdate {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *ApiKeyUpdate) ClearUpdatedByID() *ApiKeyUpdate {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiKeyUpdate) SetUpdatedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApiKeyUpdate) ClearUpdatedAt() *ApiKeyUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *ApiKeyUpdate) SetDeletedByID(v uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableDeletedByID(v *uuid.UUID) *ApiKeyUpdate {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *ApiKeyUpdate) ClearDeletedByID() *ApiKeyUpdate {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApiKeyUpdate) SetDeletedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableDeletedAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApiKeyUpdate) ClearDeletedAt() *ApiKeyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ApiKeyUpdate) SetPublishedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillablePublishedAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ApiKeyUpdate) ClearPublishedAt() *ApiKeyUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *ApiKeyUpdate) SetArchivedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableArchivedAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *ApiKeyUpdate) ClearArchivedAt() *ApiKeyUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetOwnerDomainID sets the "owner_domain_id" field.
func (_u *ApiKeyUpdate) SetOwnerDomainID(v uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetOwnerDomainID(v)
	return _u
}

// SetNillableOwnerDomainID sets the "owner_domain_id" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableOwnerDomainID(v *uuid.UUID) *ApiKeyUpdate {
	if v != nil {
		_u.SetOwnerDomainID(*v)
	}
	return _u
}

// ClearOwnerDomainID clears the value of the "owner_domain_id" field.
func (_u *ApiKeyUpdate) ClearOwnerDomainID() *ApiKeyUpdate {
	_u.mutation.ClearOwnerDomainID()
	return _u
}

// SetName sets the "name" field.
func (_u *ApiKeyUpdate) SetName(v string) *ApiKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableName(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApiKeyUpdate) SetDescription(v string) *ApiKeyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableDescription(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApiKeyUpdate) ClearDescription() *ApiKeyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetKey sets the "key" field.
func (_u *ApiKeyUpdate) SetKey(v string) *ApiKeyUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableKey(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *ApiKeyUpdate) SetSecretHash(v string) *ApiKeyUpdate {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableSecretHash(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ApiKeyUpdate) SetExpiresAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableExpiresAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ApiKeyUpdate) ClearExpiresAt() *ApiKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *ApiKeyUpdate) SetPermissions(v []string) *ApiKeyUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *ApiKeyUpdate) AppendPermissions(v []string) *ApiKeyUpdate {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *ApiKeyUpdate) ClearPermissions() *ApiKeyUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// SetDataFilters sets the "data_filters" field.
func (_u *ApiKeyUpdate) SetDataFilters(v map[string]interface{}) *ApiKeyUpdate {
	_u.mutation.SetDataFilters(v)
	return _u
}

// ClearDataFilters clears the value of the "data_filters" field.
func (_u *ApiKeyUpdate) ClearDataFilters() *ApiKeyUpdate {
	_u.mutation.ClearDataFilters()
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *ApiKeyUpdate) SetRateLimit(v int) *ApiKeyUpdate {
	_u.mutation.ResetRateLimit()
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableRateLimit(v *int) *ApiKeyUpdate {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// AddRateLimit adds value to the "rate_limit" field.
func (_u *ApiKeyUpdate) AddRateLimit(v int) *ApiKeyUpdate {
	_u.mutation.AddRateLimit(v)
	return _u
}

// SetDailyLimit sets the "daily_limit" field.
func (_u *ApiKeyUpdate) SetDailyLimit(v int) *ApiKeyUpdate {
	_u.mutation.ResetDailyLimit()
	_u.mutation.SetDailyLimit(v)
	return _u
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableDailyLimit(v *int) *ApiKeyUpdate {
	if v != nil {
		_u.SetDailyLimit(*v)
	}
	return _u
}

// AddDailyLimit adds value to the "daily_limit" field.
func (_u *ApiKeyUpdate) AddDailyLimit(v int) *ApiKeyUpdate {
	_u.mutation.AddDailyLimit(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ApiKeyUpdate) SetProjectID(v uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableProjectID(v *uuid.UUID) *ApiKeyUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *ApiKeyUpdate) ClearProjectID() *ApiKeyUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *ApiKeyUpdate) SetUsageCount(v int64) *ApiKeyUpdate {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableUsageCount(v *int64) *ApiKeyUpdate {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *ApiKeyUpdate) AddUsageCount(v int64) *ApiKeyUpdate {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ApiKeyUpdate) SetLastUsedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableLastUsedAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ApiKeyUpdate) ClearLastUsedAt() *ApiKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *ApiKeyUpdate) SetLastUsedIP(v string) *ApiKeyUpdate {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableLastUsedIP(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *ApiKeyUpdate) ClearLastUsedIP() *ApiKeyUpdate {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ApiKeyUpdate) SetIsActive(v bool) *ApiKeyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableIsActive(v *bool) *ApiKeyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ApiKeyUpdate) SetOwnerID(id uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ApiKeyUpdate) SetOwner(v *User) *ApiKeyUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (_u *ApiKeyUpdate) SetRoleID(id uuid.UUID) *ApiKeyUpdate {
	_u.mutation.SetRoleID(id)
	return _u
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableRoleID(id *uuid.UUID) *ApiKeyUpdate {
	if id != nil {
		_u = _u.SetRoleID(*id)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *ApiKeyUpdate) SetRole(v *Role) *ApiKeyUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdate) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ApiKeyUpdate) ClearOwner() *ApiKeyUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *ApiKeyUpdate) ClearRole() *ApiKeyUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := apikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := apikey.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.secret_hash": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKey.owner"`)
	}
	return nil
}

func (_u *ApiKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(apikey.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apikey.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(apikey.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(apikey.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(apikey.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(apikey.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(apikey.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(apikey.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(apikey.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(apikey.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(apikey.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerDomainID(); ok {
		_spec.SetField(apikey.FieldOwnerDomainID, field.TypeUUID, value)
	}
	if _u.mutation.OwnerDomainIDCleared() {
		_spec.ClearField(apikey.FieldOwnerDomainID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apikey.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apikey.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(apikey.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(apikey.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(apikey.FieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.DataFilters(); ok {
		_spec.SetField(apikey.FieldDataFilters, field.TypeJSON, value)
	}
	if _u.mutation.DataFiltersCleared() {
		_spec.ClearField(apikey.FieldDataFilters, field.TypeJSON)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimit(); ok {
		_spec.AddField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyLimit(); ok {
		_spec.SetField(apikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyLimit(); ok {
		_spec.AddField(apikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(apikey.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(apikey.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(apikey.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(apikey.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(apikey.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(apikey.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(apikey.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.OwnerTable,
			Columns: []string{apikey.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.OwnerTable,
			Columns: []string{apikey.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.RoleTable,
			Columns: []string{apikey.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.RoleTable,
			Columns: []string{apikey.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiKeyUpdateOne is the builder for updating a single ApiKey entity.
type ApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyMutation
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *ApiKeyUpdateOne) SetUpdatedByID(v uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableUpdatedByID(v *uuid.UUID) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *ApiKeyUpdateOne) ClearUpdatedByID() *ApiKeyUpdateOne {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiKeyUpdateOne) SetUpdatedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApiKeyUpdateOne) ClearUpdatedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *ApiKeyUpdateOne) SetDeletedByID(v uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableDeletedByID(v *uuid.UUID) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *ApiKeyUpdateOne) ClearDeletedByID() *ApiKeyUpdateOne {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApiKeyUpdateOne) SetDeletedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableDeletedAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApiKeyUpdateOne) ClearDeletedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ApiKeyUpdateOne) SetPublishedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillablePublishedAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ApiKeyUpdateOne) ClearPublishedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *ApiKeyUpdateOne) SetArchivedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableArchivedAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *ApiKeyUpdateOne) ClearArchivedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetOwnerDomainID sets the "owner_domain_id" field.
func (_u *ApiKeyUpdateOne) SetOwnerDomainID(v uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetOwnerDomainID(v)
	return _u
}

// SetNillableOwnerDomainID sets the "owner_domain_id" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableOwnerDomainID(v *uuid.UUID) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetOwnerDomainID(*v)
	}
	return _u
}

// ClearOwnerDomainID clears the value of the "owner_domain_id" field.
func (_u *ApiKeyUpdateOne) ClearOwnerDomainID() *ApiKeyUpdateOne {
	_u.mutation.ClearOwnerDomainID()
	return _u
}

// SetName sets the "name" field.
func (_u *ApiKeyUpdateOne) SetName(v string) *ApiKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableName(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApiKeyUpdateOne) SetDescription(v string) *ApiKeyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableDescription(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApiKeyUpdateOne) ClearDescription() *ApiKeyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetKey sets the "key" field.
func (_u *ApiKeyUpdateOne) SetKey(v string) *ApiKeyUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableKey(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *ApiKeyUpdateOne) SetSecretHash(v string) *ApiKeyUpdateOne {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableSecretHash(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ApiKeyUpdateOne) SetExpiresAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ApiKeyUpdateOne) ClearExpiresAt() *ApiKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *ApiKeyUpdateOne) SetPermissions(v []string) *ApiKeyUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *ApiKeyUpdateOne) AppendPermissions(v []string) *ApiKeyUpdateOne {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *ApiKeyUpdateOne) ClearPermissions() *ApiKeyUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// SetDataFilters sets the "data_filters" field.
func (_u *ApiKeyUpdateOne) SetDataFilters(v map[string]interface{}) *ApiKeyUpdateOne {
	_u.mutation.SetDataFilters(v)
	return _u
}

// ClearDataFilters clears the value of the "data_filters" field.
func (_u *ApiKeyUpdateOne) ClearDataFilters() *ApiKeyUpdateOne {
	_u.mutation.ClearDataFilters()
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *ApiKeyUpdateOne) SetRateLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.ResetRateLimit()
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableRateLimit(v *int) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// AddRateLimit adds value to the "rate_limit" field.
func (_u *ApiKeyUpdateOne) AddRateLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.AddRateLimit(v)
	return _u
}

// SetDailyLimit sets the "daily_limit" field.
func (_u *ApiKeyUpdateOne) SetDailyLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.ResetDailyLimit()
	_u.mutation.SetDailyLimit(v)
	return _u
}

// SetNillableDailyLimit sets the "daily_limit" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableDailyLimit(v *int) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetDailyLimit(*v)
	}
	return _u
}

// AddDailyLimit adds value to the "daily_limit" field.
func (_u *ApiKeyUpdateOne) AddDailyLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.AddDailyLimit(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ApiKeyUpdateOne) SetProjectID(v uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableProjectID(v *uuid.UUID) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *ApiKeyUpdateOne) ClearProjectID() *ApiKeyUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *ApiKeyUpdateOne) SetUsageCount(v int64) *ApiKeyUpdateOne {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableUsageCount(v *int64) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *ApiKeyUpdateOne) AddUsageCount(v int64) *ApiKeyUpdateOne {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ApiKeyUpdateOne) SetLastUsedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ApiKeyUpdateOne) ClearLastUsedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastUsedIP sets the "last_used_ip" field.
func (_u *ApiKeyUpdateOne) SetLastUsedIP(v string) *ApiKeyUpdateOne {
	_u.mutation.SetLastUsedIP(v)
	return _u
}

// SetNillableLastUsedIP sets the "last_used_ip" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableLastUsedIP(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedIP(*v)
	}
	return _u
}

// ClearLastUsedIP clears the value of the "last_used_ip" field.
func (_u *ApiKeyUpdateOne) ClearLastUsedIP() *ApiKeyUpdateOne {
	_u.mutation.ClearLastUsedIP()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ApiKeyUpdateOne) SetIsActive(v bool) *ApiKeyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableIsActive(v *bool) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ApiKeyUpdateOne) SetOwnerID(id uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ApiKeyUpdateOne) SetOwner(v *User) *ApiKeyUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (_u *ApiKeyUpdateOne) SetRoleID(id uuid.UUID) *ApiKeyUpdateOne {
	_u.mutation.SetRoleID(id)
	return _u
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableRoleID(id *uuid.UUID) *ApiKeyUpdateOne {
	if id != nil {
		_u = _u.SetRoleID(*id)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *ApiKeyUpdateOne) SetRole(v *Role) *ApiKeyUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdateOne) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ApiKeyUpdateOne) ClearOwner() *ApiKeyUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *ApiKeyUpdateOne) ClearRole() *ApiKeyUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdateOne) Where(ps ...predicate.ApiKey) *ApiKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiKeyUpdateOne) Select(field string, fields ...string) *ApiKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiKey entity.
func (_u *ApiKeyUpdateOne) Save(ctx context.Context) (*ApiKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) SaveX(ctx context.Context) *ApiKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := apikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := apikey.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := apikey.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.secret_hash": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKey.owner"`)
	}
	return nil
}

func (_u *ApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *ApiKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(apikey.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apikey.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(apikey.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(apikey.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(apikey.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(apikey.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(apikey.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikey.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apikey.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(apikey.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(apikey.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(apikey.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(apikey.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerDomainID(); ok {
		_spec.SetField(apikey.FieldOwnerDomainID, field.TypeUUID, value)
	}
	if _u.mutation.OwnerDomainIDCleared() {
		_spec.ClearField(apikey.FieldOwnerDomainID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apikey.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(apikey.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(apikey.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(apikey.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, apikey.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(apikey.FieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.DataFilters(); ok {
		_spec.SetField(apikey.FieldDataFilters, field.TypeJSON, value)
	}
	if _u.mutation.DataFiltersCleared() {
		_spec.ClearField(apikey.FieldDataFilters, field.TypeJSON)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimit(); ok {
		_spec.AddField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyLimit(); ok {
		_spec.SetField(apikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailyLimit(); ok {
		_spec.AddField(apikey.FieldDailyLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(apikey.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(apikey.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(apikey.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(apikey.FieldUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedIP(); ok {
		_spec.SetField(apikey.FieldLastUsedIP, field.TypeString, value)
	}
	if _u.mutation.LastUsedIPCleared() {
		_spec.ClearField(apikey.FieldLastUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(apikey.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.OwnerTable,
			Columns: []string{apikey.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikey.OwnerTable,
			Columns: []string{apikey.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.RoleTable,
			Columns: []string{apikey.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikey.RoleTable,
			Columns: []string{apikey.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
