// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/apipermissionmap"
	"github.com/leeforge/core/server/ent/predicate"
)

// APIPermissionMapUpdate is the builder for updating APIPermissionMap entities.
type APIPermissionMapUpdate struct {
	config
	hooks    []Hook
	mutation *APIPermissionMapMutation
}

// Where appends a list predicates to the APIPermissionMapUpdate builder.
func (_u *APIPermissionMapUpdate) Where(ps ...predicate.APIPermissionMap) *APIPermissionMapUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *APIPermissionMapUpdate) SetUpdatedByID(v uuid.UUID) *APIPermissionMapUpdate {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillableUpdatedByID(v *uuid.UUID) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *APIPermissionMapUpdate) ClearUpdatedByID() *APIPermissionMapUpdate {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIPermissionMapUpdate) SetUpdatedAt(v time.Time) *APIPermissionMapUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *APIPermissionMapUpdate) ClearUpdatedAt() *APIPermissionMapUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *APIPermissionMapUpdate) SetDeletedByID(v uuid.UUID) *APIPermissionMapUpdate {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillableDeletedByID(v *uuid.UUID) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *APIPermissionMapUpdate) ClearDeletedByID() *APIPermissionMapUpdate {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIPermissionMapUpdate) SetDeletedAt(v time.Time) *APIPermissionMapUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillableDeletedAt(v *time.Time) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIPermissionMapUpdate) ClearDeletedAt() *APIPermissionMapUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *APIPermissionMapUpdate) SetPublishedAt(v time.Time) *APIPermissionMapUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillablePublishedAt(v *time.Time) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *APIPermissionMapUpdate) ClearPublishedAt() *APIPermissionMapUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *APIPermissionMapUpdate) SetArchivedAt(v time.Time) *APIPermissionMapUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillableArchivedAt(v *time.Time) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *APIPermissionMapUpdate) ClearArchivedAt() *APIPermissionMapUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetAPIID sets the "api_id" field.
func (_u *APIPermissionMapUpdate) SetAPIID(v uuid.UUID) *APIPermissionMapUpdate {
	_u.mutation.SetAPIID(v)
	return _u
}

// SetNillableAPIID sets the "api_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillableAPIID(v *uuid.UUID) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetAPIID(*v)
	}
	return _u
}

// SetPermissionCode sets the "permission_code" field.
func (_u *APIPermissionMapUpdate) SetPermissionCode(v string) *APIPermissionMapUpdate {
	_u.mutation.SetPermissionCode(v)
	return _u
}

// SetNillablePermissionCode sets the "permission_code" field if the given value is not nil.
func (_u *APIPermissionMapUpdate) SetNillablePermissionCode(v *string) *APIPermissionMapUpdate {
	if v != nil {
		_u.SetPermissionCode(*v)
	}
	return _u
}

// Mutation returns the APIPermissionMapMutation object of the builder.
func (_u *APIPermissionMapUpdate) Mutation() *APIPermissionMapMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIPermissionMapUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIPermissionMapUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIPermissionMapUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIPermissionMapUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIPermissionMapUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := apipermissionmap.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIPermissionMapUpdate) check() error {
	if v, ok := _u.mutation.PermissionCode(); ok {
		if err := apipermissionmap.PermissionCodeValidator(v); err != nil {
			return &ValidationError{Name: "permission_code", err: fmt.Errorf(`ent: validator failed for field "APIPermissionMap.permission_code": %w`, err)}
		}
	}
	return nil
}

func (_u *APIPermissionMapUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apipermissionmap.Table, apipermissionmap.Columns, sqlgraph.NewFieldSpec(apipermissionmap.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(apipermissionmap.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apipermissionmap.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(apipermissionmap.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apipermissionmap.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(apipermissionmap.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(apipermissionmap.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.APIID(); ok {
		_spec.SetField(apipermissionmap.FieldAPIID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PermissionCode(); ok {
		_spec.SetField(apipermissionmap.FieldPermissionCode, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apipermissionmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIPermissionMapUpdateOne is the builder for updating a single APIPermissionMap entity.
type APIPermissionMapUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIPermissionMapMutation
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *APIPermissionMapUpdateOne) SetUpdatedByID(v uuid.UUID) *APIPermissionMapUpdateOne {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillableUpdatedByID(v *uuid.UUID) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *APIPermissionMapUpdateOne) ClearUpdatedByID() *APIPermissionMapUpdateOne {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIPermissionMapUpdateOne) SetUpdatedAt(v time.Time) *APIPermissionMapUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *APIPermissionMapUpdateOne) ClearUpdatedAt() *APIPermissionMapUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *APIPermissionMapUpdateOne) SetDeletedByID(v uuid.UUID) *APIPermissionMapUpdateOne {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillableDeletedByID(v *uuid.UUID) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *APIPermissionMapUpdateOne) ClearDeletedByID() *APIPermissionMapUpdateOne {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIPermissionMapUpdateOne) SetDeletedAt(v time.Time) *APIPermissionMapUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillableDeletedAt(v *time.Time) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIPermissionMapUpdateOne) ClearDeletedAt() *APIPermissionMapUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *APIPermissionMapUpdateOne) SetPublishedAt(v time.Time) *APIPermissionMapUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillablePublishedAt(v *time.Time) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *APIPermissionMapUpdateOne) ClearPublishedAt() *APIPermissionMapUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *APIPermissionMapUpdateOne) SetArchivedAt(v time.Time) *APIPermissionMapUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillableArchivedAt(v *time.Time) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *APIPermissionMapUpdateOne) ClearArchivedAt() *APIPermissionMapUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetAPIID sets the "api_id" field.
func (_u *APIPermissionMapUpdateOne) SetAPIID(v uuid.UUID) *APIPermissionMapUpdateOne {
	_u.mutation.SetAPIID(v)
	return _u
}

// SetNillableAPIID sets the "api_id" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillableAPIID(v *uuid.UUID) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetAPIID(*v)
	}
	return _u
}

// SetPermissionCode sets the "permission_code" field.
func (_u *APIPermissionMapUpdateOne) SetPermissionCode(v string) *APIPermissionMapUpdateOne {
	_u.mutation.SetPermissionCode(v)
	return _u
}

// SetNillablePermissionCode sets the "permission_code" field if the given value is not nil.
func (_u *APIPermissionMapUpdateOne) SetNillablePermissionCode(v *string) *APIPermissionMapUpdateOne {
	if v != nil {
		_u.SetPermissionCode(*v)
	}
	return _u
}

// Mutation returns the APIPermissionMapMutation object of the builder.
func (_u *APIPermissionMapUpdateOne) Mutation() *APIPermissionMapMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIPermissionMapUpdate builder.
func (_u *APIPermissionMapUpdateOne) Where(ps ...predicate.APIPermissionMap) *APIPermissionMapUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIPermissionMapUpdateOne) Select(field string, fields ...string) *APIPermissionMapUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIPermissionMap entity.
func (_u *APIPermissionMapUpdateOne) Save(ctx context.Context) (*APIPermissionMap, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIPermissionMapUpdateOne) SaveX(ctx context.Context) *APIPermissionMap {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIPermissionMapUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIPermissionMapUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIPermissionMapUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := apipermissionmap.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIPermissionMapUpdateOne) check() error {
	if v, ok := _u.mutation.PermissionCode(); ok {
		if err := apipermissionmap.PermissionCodeValidator(v); err != nil {
			return &ValidationError{Name: "permission_code", err: fmt.Errorf(`ent: validator failed for field "APIPermissionMap.permission_code": %w`, err)}
		}
	}
	return nil
}

func (_u *APIPermissionMapUpdateOne) sqlSave(ctx context.Context) (_node *APIPermissionMap, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apipermissionmap.Table, apipermissionmap.Columns, sqlgraph.NewFieldSpec(apipermissionmap.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIPermissionMap.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apipermissionmap.FieldID)
		for _, f := range fields {
			if !apipermissionmap.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apipermissionmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(apipermissionmap.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apipermissionmap.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(apipermissionmap.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(apipermissionmap.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apipermissionmap.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(apipermissionmap.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(apipermissionmap.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(apipermissionmap.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.APIID(); ok {
		_spec.SetField(apipermissionmap.FieldAPIID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PermissionCode(); ok {
		_spec.SetField(apipermissionmap.FieldPermissionCode, field.TypeString, value)
	}
	_node = &APIPermissionMap{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apipermissionmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
