// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/domain"
	"github.com/leeforge/core/server/ent/domainmembership"
	"github.com/leeforge/core/server/ent/predicate"
)

// DomainMembershipUpdate is the builder for updating DomainMembership entities.
type DomainMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *DomainMembershipMutation
}

// Where appends a list predicates to the DomainMembershipUpdate builder.
func (_u *DomainMembershipUpdate) Where(ps ...predicate.DomainMembership) *DomainMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *DomainMembershipUpdate) SetUpdatedByID(v uuid.UUID) *DomainMembershipUpdate {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableUpdatedByID(v *uuid.UUID) *DomainMembershipUpdate {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *DomainMembershipUpdate) ClearUpdatedByID() *DomainMembershipUpdate {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DomainMembershipUpdate) SetUpdatedAt(v time.Time) *DomainMembershipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DomainMembershipUpdate) ClearUpdatedAt() *DomainMembershipUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *DomainMembershipUpdate) SetDeletedByID(v uuid.UUID) *DomainMembershipUpdate {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableDeletedByID(v *uuid.UUID) *DomainMembershipUpdate {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *DomainMembershipUpdate) ClearDeletedByID() *DomainMembershipUpdate {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DomainMembershipUpdate) SetDeletedAt(v time.Time) *DomainMembershipUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableDeletedAt(v *time.Time) *DomainMembershipUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DomainMembershipUpdate) ClearDeletedAt() *DomainMembershipUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *DomainMembershipUpdate) SetPublishedAt(v time.Time) *DomainMembershipUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillablePublishedAt(v *time.Time) *DomainMembershipUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *DomainMembershipUpdate) ClearPublishedAt() *DomainMembershipUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *DomainMembershipUpdate) SetArchivedAt(v time.Time) *DomainMembershipUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableArchivedAt(v *time.Time) *DomainMembershipUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *DomainMembershipUpdate) ClearArchivedAt() *DomainMembershipUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetDomainID sets the "domain_id" field.
func (_u *DomainMembershipUpdate) SetDomainID(v uuid.UUID) *DomainMembershipUpdate {
	_u.mutation.SetDomainID(v)
	return _u
}

// SetNillableDomainID sets the "domain_id" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableDomainID(v *uuid.UUID) *DomainMembershipUpdate {
	if v != nil {
		_u.SetDomainID(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *DomainMembershipUpdate) SetSubjectType(v domainmembership.SubjectType) *DomainMembershipUpdate {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableSubjectType(v *domainmembership.SubjectType) *DomainMembershipUpdate {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *DomainMembershipUpdate) SetSubjectID(v uuid.UUID) *DomainMembershipUpdate {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableSubjectID(v *uuid.UUID) *DomainMembershipUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetMemberRole sets the "member_role" field.
func (_u *DomainMembershipUpdate) SetMemberRole(v string) *DomainMembershipUpdate {
	_u.mutation.SetMemberRole(v)
	return _u
}

// SetNillableMemberRole sets the "member_role" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableMemberRole(v *string) *DomainMembershipUpdate {
	if v != nil {
		_u.SetMemberRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DomainMembershipUpdate) SetStatus(v domainmembership.Status) *DomainMembershipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableStatus(v *domainmembership.Status) *DomainMembershipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *DomainMembershipUpdate) SetIsDefault(v bool) *DomainMembershipUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *DomainMembershipUpdate) SetNillableIsDefault(v *bool) *DomainMembershipUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetDomain sets the "domain" edge to the Domain entity.
func (_u *DomainMembershipUpdate) SetDomain(v *Domain) *DomainMembershipUpdate {
	return _u.SetDomainID(v.ID)
}

// Mutation returns the DomainMembershipMutation object of the builder.
func (_u *DomainMembershipUpdate) Mutation() *DomainMembershipMutation {
	return _u.mutation
}

// ClearDomain clears the "domain" edge to the Domain entity.
func (_u *DomainMembershipUpdate) ClearDomain() *DomainMembershipUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DomainMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DomainMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DomainMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := domainmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DomainMembershipUpdate) check() error {
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := domainmembership.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberRole(); ok {
		if err := domainmembership.MemberRoleValidator(v); err != nil {
			return &ValidationError{Name: "member_role", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.member_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := domainmembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.status": %w`, err)}
		}
	}
	if _u.mutation.DomainCleared() && len(_u.mutation.DomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DomainMembership.domain"`)
	}
	return nil
}

func (_u *DomainMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(domainmembership.Table, domainmembership.Columns, sqlgraph.NewFieldSpec(domainmembership.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(domainmembership.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(domainmembership.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(domainmembership.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(domainmembership.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(domainmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(domainmembership.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(domainmembership.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(domainmembership.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(domainmembership.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(domainmembership.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(domainmembership.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(domainmembership.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(domainmembership.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(domainmembership.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(domainmembership.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(domainmembership.FieldSubjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MemberRole(); ok {
		_spec.SetField(domainmembership.FieldMemberRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(domainmembership.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(domainmembership.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.DomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainmembership.DomainTable,
			Columns: []string{domainmembership.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainmembership.DomainTable,
			Columns: []string{domainmembership.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domainmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DomainMembershipUpdateOne is the builder for updating a single DomainMembership entity.
type DomainMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DomainMembershipMutation
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_u *DomainMembershipUpdateOne) SetUpdatedByID(v uuid.UUID) *DomainMembershipUpdateOne {
	_u.mutation.SetUpdatedByID(v)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableUpdatedByID(v *uuid.UUID) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetUpdatedByID(*v)
	}
	return _u
}

// ClearUpdatedByID clears the value of the "updated_by_id" field.
func (_u *DomainMembershipUpdateOne) ClearUpdatedByID() *DomainMembershipUpdateOne {
	_u.mutation.ClearUpdatedByID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DomainMembershipUpdateOne) SetUpdatedAt(v time.Time) *DomainMembershipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DomainMembershipUpdateOne) ClearUpdatedAt() *DomainMembershipUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_u *DomainMembershipUpdateOne) SetDeletedByID(v uuid.UUID) *DomainMembershipUpdateOne {
	_u.mutation.SetDeletedByID(v)
	return _u
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableDeletedByID(v *uuid.UUID) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetDeletedByID(*v)
	}
	return _u
}

// ClearDeletedByID clears the value of the "deleted_by_id" field.
func (_u *DomainMembershipUpdateOne) ClearDeletedByID() *DomainMembershipUpdateOne {
	_u.mutation.ClearDeletedByID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DomainMembershipUpdateOne) SetDeletedAt(v time.Time) *DomainMembershipUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableDeletedAt(v *time.Time) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DomainMembershipUpdateOne) ClearDeletedAt() *DomainMembershipUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *DomainMembershipUpdateOne) SetPublishedAt(v time.Time) *DomainMembershipUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillablePublishedAt(v *time.Time) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *DomainMembershipUpdateOne) ClearPublishedAt() *DomainMembershipUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *DomainMembershipUpdateOne) SetArchivedAt(v time.Time) *DomainMembershipUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableArchivedAt(v *time.Time) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *DomainMembershipUpdateOne) ClearArchivedAt() *DomainMembershipUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetDomainID sets the "domain_id" field.
func (_u *DomainMembershipUpdateOne) SetDomainID(v uuid.UUID) *DomainMembershipUpdateOne {
	_u.mutation.SetDomainID(v)
	return _u
}

// SetNillableDomainID sets the "domain_id" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableDomainID(v *uuid.UUID) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetDomainID(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *DomainMembershipUpdateOne) SetSubjectType(v domainmembership.SubjectType) *DomainMembershipUpdateOne {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableSubjectType(v *domainmembership.SubjectType) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *DomainMembershipUpdateOne) SetSubjectID(v uuid.UUID) *DomainMembershipUpdateOne {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableSubjectID(v *uuid.UUID) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetMemberRole sets the "member_role" field.
func (_u *DomainMembershipUpdateOne) SetMemberRole(v string) *DomainMembershipUpdateOne {
	_u.mutation.SetMemberRole(v)
	return _u
}

// SetNillableMemberRole sets the "member_role" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableMemberRole(v *string) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetMemberRole(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DomainMembershipUpdateOne) SetStatus(v domainmembership.Status) *DomainMembershipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableStatus(v *domainmembership.Status) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *DomainMembershipUpdateOne) SetIsDefault(v bool) *DomainMembershipUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *DomainMembershipUpdateOne) SetNillableIsDefault(v *bool) *DomainMembershipUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetDomain sets the "domain" edge to the Domain entity.
func (_u *DomainMembershipUpdateOne) SetDomain(v *Domain) *DomainMembershipUpdateOne {
	return _u.SetDomainID(v.ID)
}

// Mutation returns the DomainMembershipMutation object of the builder.
func (_u *DomainMembershipUpdateOne) Mutation() *DomainMembershipMutation {
	return _u.mutation
}

// ClearDomain clears the "domain" edge to the Domain entity.
func (_u *DomainMembershipUpdateOne) ClearDomain() *DomainMembershipUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// Where appends a list predicates to the DomainMembershipUpdate builder.
func (_u *DomainMembershipUpdateOne) Where(ps ...predicate.DomainMembership) *DomainMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DomainMembershipUpdateOne) Select(field string, fields ...string) *DomainMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DomainMembership entity.
func (_u *DomainMembershipUpdateOne) Save(ctx context.Context) (*DomainMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DomainMembershipUpdateOne) SaveX(ctx context.Context) *DomainMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DomainMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DomainMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DomainMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := domainmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DomainMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := domainmembership.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberRole(); ok {
		if err := domainmembership.MemberRoleValidator(v); err != nil {
			return &ValidationError{Name: "member_role", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.member_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := domainmembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DomainMembership.status": %w`, err)}
		}
	}
	if _u.mutation.DomainCleared() && len(_u.mutation.DomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DomainMembership.domain"`)
	}
	return nil
}

func (_u *DomainMembershipUpdateOne) sqlSave(ctx context.Context) (_node *DomainMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(domainmembership.Table, domainmembership.Columns, sqlgraph.NewFieldSpec(domainmembership.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DomainMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domainmembership.FieldID)
		for _, f := range fields {
			if !domainmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != domainmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedByIDCleared() {
		_spec.ClearField(domainmembership.FieldCreatedByID, field.TypeUUID)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(domainmembership.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedByID(); ok {
		_spec.SetField(domainmembership.FieldUpdatedByID, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByIDCleared() {
		_spec.ClearField(domainmembership.FieldUpdatedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(domainmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(domainmembership.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedByID(); ok {
		_spec.SetField(domainmembership.FieldDeletedByID, field.TypeUUID, value)
	}
	if _u.mutation.DeletedByIDCleared() {
		_spec.ClearField(domainmembership.FieldDeletedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(domainmembership.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(domainmembership.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(domainmembership.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(domainmembership.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(domainmembership.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(domainmembership.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(domainmembership.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(domainmembership.FieldSubjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.MemberRole(); ok {
		_spec.SetField(domainmembership.FieldMemberRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(domainmembership.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(domainmembership.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.DomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainmembership.DomainTable,
			Columns: []string{domainmembership.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domainmembership.DomainTable,
			Columns: []string{domainmembership.DomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domain.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DomainMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domainmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
