// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/mediafolder"
)

// MediaFolder is the model entity for the MediaFolder schema.
type MediaFolder struct {
	config `json:"-"`
	// ID of the ent.
	// 唯一标识
	ID uuid.UUID `json:"id"`
	// 创建者ID
	CreatedByID uuid.UUID `json:"createdById,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// 更新者ID
	UpdatedByID uuid.UUID `json:"updatedById,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// 删除者ID
	DeletedByID uuid.UUID `json:"deletedById,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deletedAt,omitempty"`
	// 发布时间
	PublishedAt time.Time `json:"publishedAt,omitempty"`
	// 归档时间
	ArchivedAt time.Time `json:"archivedAt,omitempty"`
	// Owner domain ID for domain-based isolation
	OwnerDomainID *uuid.UUID `json:"ownerDomainId,omitempty"`
	// 目录名
	Name string `json:"name,omitempty"`
	// 目录路径
	Path string `json:"path,omitempty"`
	// 目录深度
	Depth int `json:"depth,omitempty"`
	// 父目录ID
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MediaFolderQuery when eager-loading is set.
	Edges        MediaFolderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MediaFolderEdges holds the relations/edges for other nodes in the graph.
type MediaFolderEdges struct {
	// 父目录
	Parent *MediaFolder `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*MediaFolder `json:"children,omitempty"`
	// 目录下文件
	Files []*Media `json:"files,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MediaFolderEdges) ParentOrErr() (*MediaFolder, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mediafolder.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e MediaFolderEdges) ChildrenOrErr() ([]*MediaFolder, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e MediaFolderEdges) FilesOrErr() ([]*Media, error) {
	if e.loadedTypes[2] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaFolder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediafolder.FieldOwnerDomainID, mediafolder.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case mediafolder.FieldDepth:
			values[i] = new(sql.NullInt64)
		case mediafolder.FieldName, mediafolder.FieldPath:
			values[i] = new(sql.NullString)
		case mediafolder.FieldCreatedAt, mediafolder.FieldUpdatedAt, mediafolder.FieldDeletedAt, mediafolder.FieldPublishedAt, mediafolder.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case mediafolder.FieldID, mediafolder.FieldCreatedByID, mediafolder.FieldUpdatedByID, mediafolder.FieldDeletedByID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaFolder fields.
func (_m *MediaFolder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediafolder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mediafolder.FieldCreatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value != nil {
				_m.CreatedByID = *value
			}
		case mediafolder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediafolder.FieldUpdatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value != nil {
				_m.UpdatedByID = *value
			}
		case mediafolder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediafolder.FieldDeletedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by_id", values[i])
			} else if value != nil {
				_m.DeletedByID = *value
			}
		case mediafolder.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case mediafolder.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		case mediafolder.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = value.Time
			}
		case mediafolder.FieldOwnerDomainID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_domain_id", values[i])
			} else if value.Valid {
				_m.OwnerDomainID = new(uuid.UUID)
				*_m.OwnerDomainID = *value.S.(*uuid.UUID)
			}
		case mediafolder.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case mediafolder.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case mediafolder.FieldDepth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field depth", values[i])
			} else if value.Valid {
				_m.Depth = int(value.Int64)
			}
		case mediafolder.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uuid.UUID)
				*_m.ParentID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaFolder.
// This includes values selected through modifiers, order, etc.
func (_m *MediaFolder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the MediaFolder entity.
func (_m *MediaFolder) QueryParent() *MediaFolderQuery {
	return NewMediaFolderClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the MediaFolder entity.
func (_m *MediaFolder) QueryChildren() *MediaFolderQuery {
	return NewMediaFolderClient(_m.config).QueryChildren(_m)
}

// QueryFiles queries the "files" edge of the MediaFolder entity.
func (_m *MediaFolder) QueryFiles() *MediaQuery {
	return NewMediaFolderClient(_m.config).QueryFiles(_m)
}

// Update returns a builder for updating this MediaFolder.
// Note that you need to call MediaFolder.Unwrap() before calling this method if this MediaFolder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaFolder) Update() *MediaFolderUpdateOne {
	return NewMediaFolderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaFolder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaFolder) Unwrap() *MediaFolder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaFolder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaFolder) String() string {
	var builder strings.Builder
	builder.WriteString("MediaFolder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByID))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedByID))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("archived_at=")
	builder.WriteString(_m.ArchivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OwnerDomainID; v != nil {
		builder.WriteString("owner_domain_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("depth=")
	builder.WriteString(fmt.Sprintf("%v", _m.Depth))
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaFolders is a parsable slice of MediaFolder.
type MediaFolders []*MediaFolder
