// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/systemerror"
	"github.com/leeforge/core/server/ent/user"
)

// SystemError is the model entity for the SystemError schema.
type SystemError struct {
	config `json:"-"`
	// ID of the ent.
	// 唯一标识
	ID uuid.UUID `json:"id"`
	// 创建者ID
	CreatedByID uuid.UUID `json:"createdById,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// 更新者ID
	UpdatedByID uuid.UUID `json:"updatedById,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// 删除者ID
	DeletedByID uuid.UUID `json:"deletedById,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deletedAt,omitempty"`
	// 发布时间
	PublishedAt time.Time `json:"publishedAt,omitempty"`
	// 归档时间
	ArchivedAt time.Time `json:"archivedAt,omitempty"`
	// Owner domain ID for domain-based isolation
	OwnerDomainID *uuid.UUID `json:"ownerDomainId,omitempty"`
	// 错误级别
	ErrorLevel systemerror.ErrorLevel `json:"errorLevel"`
	// 错误类型
	ErrorType string `json:"errorType"`
	// 错误信息
	ErrorMsg string `json:"errorMsg"`
	// 堆栈信息
	ErrorStack string `json:"errorStack,omitempty"`
	// 错误码
	ErrorCode string `json:"errorCode,omitempty"`
	// 请求追踪ID
	RequestID string `json:"requestId,omitempty"`
	// RequestMethod holds the value of the "request_method" field.
	RequestMethod string `json:"requestMethod,omitempty"`
	// RequestPath holds the value of the "request_path" field.
	RequestPath string `json:"requestPath,omitempty"`
	// 请求体
	RequestBody string `json:"requestBody,omitempty"`
	// 响应体
	ResponseBody string `json:"responseBody,omitempty"`
	// 触发用户ID
	UserID *uuid.UUID `json:"userId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SystemErrorQuery when eager-loading is set.
	Edges        SystemErrorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SystemErrorEdges holds the relations/edges for other nodes in the graph.
type SystemErrorEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SystemErrorEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SystemError) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systemerror.FieldOwnerDomainID, systemerror.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case systemerror.FieldErrorLevel, systemerror.FieldErrorType, systemerror.FieldErrorMsg, systemerror.FieldErrorStack, systemerror.FieldErrorCode, systemerror.FieldRequestID, systemerror.FieldRequestMethod, systemerror.FieldRequestPath, systemerror.FieldRequestBody, systemerror.FieldResponseBody:
			values[i] = new(sql.NullString)
		case systemerror.FieldCreatedAt, systemerror.FieldUpdatedAt, systemerror.FieldDeletedAt, systemerror.FieldPublishedAt, systemerror.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case systemerror.FieldID, systemerror.FieldCreatedByID, systemerror.FieldUpdatedByID, systemerror.FieldDeletedByID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SystemError fields.
func (_m *SystemError) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systemerror.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case systemerror.FieldCreatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value != nil {
				_m.CreatedByID = *value
			}
		case systemerror.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case systemerror.FieldUpdatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value != nil {
				_m.UpdatedByID = *value
			}
		case systemerror.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case systemerror.FieldDeletedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by_id", values[i])
			} else if value != nil {
				_m.DeletedByID = *value
			}
		case systemerror.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case systemerror.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		case systemerror.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = value.Time
			}
		case systemerror.FieldOwnerDomainID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_domain_id", values[i])
			} else if value.Valid {
				_m.OwnerDomainID = new(uuid.UUID)
				*_m.OwnerDomainID = *value.S.(*uuid.UUID)
			}
		case systemerror.FieldErrorLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_level", values[i])
			} else if value.Valid {
				_m.ErrorLevel = systemerror.ErrorLevel(value.String)
			}
		case systemerror.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				_m.ErrorType = value.String
			}
		case systemerror.FieldErrorMsg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_msg", values[i])
			} else if value.Valid {
				_m.ErrorMsg = value.String
			}
		case systemerror.FieldErrorStack:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_stack", values[i])
			} else if value.Valid {
				_m.ErrorStack = value.String
			}
		case systemerror.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case systemerror.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case systemerror.FieldRequestMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_method", values[i])
			} else if value.Valid {
				_m.RequestMethod = value.String
			}
		case systemerror.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				_m.RequestPath = value.String
			}
		case systemerror.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = value.String
			}
		case systemerror.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = value.String
			}
		case systemerror.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SystemError.
// This includes values selected through modifiers, order, etc.
func (_m *SystemError) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SystemError entity.
func (_m *SystemError) QueryUser() *UserQuery {
	return NewSystemErrorClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this SystemError.
// Note that you need to call SystemError.Unwrap() before calling this method if this SystemError
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SystemError) Update() *SystemErrorUpdateOne {
	return NewSystemErrorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SystemError entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SystemError) Unwrap() *SystemError {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SystemError is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SystemError) String() string {
	var builder strings.Builder
	builder.WriteString("SystemError(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByID))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedByID))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("archived_at=")
	builder.WriteString(_m.ArchivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OwnerDomainID; v != nil {
		builder.WriteString("owner_domain_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("error_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorLevel))
	builder.WriteString(", ")
	builder.WriteString("error_type=")
	builder.WriteString(_m.ErrorType)
	builder.WriteString(", ")
	builder.WriteString("error_msg=")
	builder.WriteString(_m.ErrorMsg)
	builder.WriteString(", ")
	builder.WriteString("error_stack=")
	builder.WriteString(_m.ErrorStack)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("request_method=")
	builder.WriteString(_m.RequestMethod)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(_m.RequestPath)
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(_m.RequestBody)
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(_m.ResponseBody)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SystemErrors is a parsable slice of SystemError.
type SystemErrors []*SystemError
