// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/tenantuser"
	"github.com/leeforge/core/server/ent/user"
)

// TenantUser is the model entity for the TenantUser schema.
type TenantUser struct {
	config `json:"-"`
	// ID of the ent.
	// 唯一标识
	ID uuid.UUID `json:"id"`
	// 创建者ID
	CreatedByID uuid.UUID `json:"createdById,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// 更新者ID
	UpdatedByID uuid.UUID `json:"updatedById,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// 删除者ID
	DeletedByID uuid.UUID `json:"deletedById,omitempty"`
	// 删除时间
	DeletedAt time.Time `json:"deletedAt,omitempty"`
	// 发布时间
	PublishedAt time.Time `json:"publishedAt,omitempty"`
	// 归档时间
	ArchivedAt time.Time `json:"archivedAt,omitempty"`
	// 所属租户ID
	TenantID uuid.UUID `json:"tenantId"`
	// 用户ID
	UserID uuid.UUID `json:"user_id,omitempty"`
	// 租户内角色
	Role string `json:"role,omitempty"`
	// 成员状态
	Status tenantuser.Status `json:"status,omitempty"`
	// 是否默认租户
	IsDefault bool `json:"is_default,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantUserQuery when eager-loading is set.
	Edges        TenantUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantUserEdges holds the relations/edges for other nodes in the graph.
type TenantUserEdges struct {
	// 所属用户
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantuser.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case tenantuser.FieldRole, tenantuser.FieldStatus:
			values[i] = new(sql.NullString)
		case tenantuser.FieldCreatedAt, tenantuser.FieldUpdatedAt, tenantuser.FieldDeletedAt, tenantuser.FieldPublishedAt, tenantuser.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case tenantuser.FieldID, tenantuser.FieldCreatedByID, tenantuser.FieldUpdatedByID, tenantuser.FieldDeletedByID, tenantuser.FieldTenantID, tenantuser.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantUser fields.
func (_m *TenantUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tenantuser.FieldCreatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value != nil {
				_m.CreatedByID = *value
			}
		case tenantuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tenantuser.FieldUpdatedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_id", values[i])
			} else if value != nil {
				_m.UpdatedByID = *value
			}
		case tenantuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tenantuser.FieldDeletedByID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by_id", values[i])
			} else if value != nil {
				_m.DeletedByID = *value
			}
		case tenantuser.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case tenantuser.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		case tenantuser.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = value.Time
			}
		case tenantuser.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case tenantuser.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case tenantuser.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case tenantuser.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = tenantuser.Status(value.String)
			}
		case tenantuser.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantUser.
// This includes values selected through modifiers, order, etc.
func (_m *TenantUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TenantUser entity.
func (_m *TenantUser) QueryUser() *UserQuery {
	return NewTenantUserClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TenantUser.
// Note that you need to call TenantUser.Unwrap() before calling this method if this TenantUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantUser) Update() *TenantUserUpdateOne {
	return NewTenantUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantUser) Unwrap() *TenantUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantUser) String() string {
	var builder strings.Builder
	builder.WriteString("TenantUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByID))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedByID))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("archived_at=")
	builder.WriteString(_m.ArchivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteByte(')')
	return builder.String()
}

// TenantUsers is a parsable slice of TenantUser.
type TenantUsers []*TenantUser
