// Code generated by ent, DO NOT EDIT.

package dictionarydetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldID, id))
}

// CreatedByID applies equality check predicate on the "created_by_id" field. It's identical to CreatedByIDEQ.
func CreatedByID(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedByID applies equality check predicate on the "updated_by_id" field. It's identical to UpdatedByIDEQ.
func UpdatedByID(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedByID applies equality check predicate on the "deleted_by_id" field. It's identical to DeletedByIDEQ.
func DeletedByID(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDeletedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldPublishedAt, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldArchivedAt, v))
}

// OwnerDomainID applies equality check predicate on the "owner_domain_id" field. It's identical to OwnerDomainIDEQ.
func OwnerDomainID(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldOwnerDomainID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldValue, v))
}

// Extend applies equality check predicate on the "extend" field. It's identical to ExtendEQ.
func Extend(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldExtend, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldSort, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v bool) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldStatus, v))
}

// DictionaryID applies equality check predicate on the "dictionary_id" field. It's identical to DictionaryIDEQ.
func DictionaryID(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDictionaryID, v))
}

// CreatedByIDEQ applies the EQ predicate on the "created_by_id" field.
func CreatedByIDEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedByIDNEQ applies the NEQ predicate on the "created_by_id" field.
func CreatedByIDNEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldCreatedByID, v))
}

// CreatedByIDIn applies the In predicate on the "created_by_id" field.
func CreatedByIDIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldCreatedByID, vs...))
}

// CreatedByIDNotIn applies the NotIn predicate on the "created_by_id" field.
func CreatedByIDNotIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldCreatedByID, vs...))
}

// CreatedByIDGT applies the GT predicate on the "created_by_id" field.
func CreatedByIDGT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldCreatedByID, v))
}

// CreatedByIDGTE applies the GTE predicate on the "created_by_id" field.
func CreatedByIDGTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldCreatedByID, v))
}

// CreatedByIDLT applies the LT predicate on the "created_by_id" field.
func CreatedByIDLT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldCreatedByID, v))
}

// CreatedByIDLTE applies the LTE predicate on the "created_by_id" field.
func CreatedByIDLTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldCreatedByID, v))
}

// CreatedByIDIsNil applies the IsNil predicate on the "created_by_id" field.
func CreatedByIDIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldCreatedByID))
}

// CreatedByIDNotNil applies the NotNil predicate on the "created_by_id" field.
func CreatedByIDNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldCreatedByID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByIDEQ applies the EQ predicate on the "updated_by_id" field.
func UpdatedByIDEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedByIDNEQ applies the NEQ predicate on the "updated_by_id" field.
func UpdatedByIDNEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldUpdatedByID, v))
}

// UpdatedByIDIn applies the In predicate on the "updated_by_id" field.
func UpdatedByIDIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDNotIn applies the NotIn predicate on the "updated_by_id" field.
func UpdatedByIDNotIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDGT applies the GT predicate on the "updated_by_id" field.
func UpdatedByIDGT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldUpdatedByID, v))
}

// UpdatedByIDGTE applies the GTE predicate on the "updated_by_id" field.
func UpdatedByIDGTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldUpdatedByID, v))
}

// UpdatedByIDLT applies the LT predicate on the "updated_by_id" field.
func UpdatedByIDLT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldUpdatedByID, v))
}

// UpdatedByIDLTE applies the LTE predicate on the "updated_by_id" field.
func UpdatedByIDLTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldUpdatedByID, v))
}

// UpdatedByIDIsNil applies the IsNil predicate on the "updated_by_id" field.
func UpdatedByIDIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldUpdatedByID))
}

// UpdatedByIDNotNil applies the NotNil predicate on the "updated_by_id" field.
func UpdatedByIDNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldUpdatedByID))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByIDEQ applies the EQ predicate on the "deleted_by_id" field.
func DeletedByIDEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedByIDNEQ applies the NEQ predicate on the "deleted_by_id" field.
func DeletedByIDNEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldDeletedByID, v))
}

// DeletedByIDIn applies the In predicate on the "deleted_by_id" field.
func DeletedByIDIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldDeletedByID, vs...))
}

// DeletedByIDNotIn applies the NotIn predicate on the "deleted_by_id" field.
func DeletedByIDNotIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldDeletedByID, vs...))
}

// DeletedByIDGT applies the GT predicate on the "deleted_by_id" field.
func DeletedByIDGT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldDeletedByID, v))
}

// DeletedByIDGTE applies the GTE predicate on the "deleted_by_id" field.
func DeletedByIDGTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldDeletedByID, v))
}

// DeletedByIDLT applies the LT predicate on the "deleted_by_id" field.
func DeletedByIDLT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldDeletedByID, v))
}

// DeletedByIDLTE applies the LTE predicate on the "deleted_by_id" field.
func DeletedByIDLTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldDeletedByID, v))
}

// DeletedByIDIsNil applies the IsNil predicate on the "deleted_by_id" field.
func DeletedByIDIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldDeletedByID))
}

// DeletedByIDNotNil applies the NotNil predicate on the "deleted_by_id" field.
func DeletedByIDNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldDeletedByID))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldDeletedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldPublishedAt))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldArchivedAt))
}

// OwnerDomainIDEQ applies the EQ predicate on the "owner_domain_id" field.
func OwnerDomainIDEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldOwnerDomainID, v))
}

// OwnerDomainIDNEQ applies the NEQ predicate on the "owner_domain_id" field.
func OwnerDomainIDNEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldOwnerDomainID, v))
}

// OwnerDomainIDIn applies the In predicate on the "owner_domain_id" field.
func OwnerDomainIDIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldOwnerDomainID, vs...))
}

// OwnerDomainIDNotIn applies the NotIn predicate on the "owner_domain_id" field.
func OwnerDomainIDNotIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldOwnerDomainID, vs...))
}

// OwnerDomainIDGT applies the GT predicate on the "owner_domain_id" field.
func OwnerDomainIDGT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldOwnerDomainID, v))
}

// OwnerDomainIDGTE applies the GTE predicate on the "owner_domain_id" field.
func OwnerDomainIDGTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldOwnerDomainID, v))
}

// OwnerDomainIDLT applies the LT predicate on the "owner_domain_id" field.
func OwnerDomainIDLT(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldOwnerDomainID, v))
}

// OwnerDomainIDLTE applies the LTE predicate on the "owner_domain_id" field.
func OwnerDomainIDLTE(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldOwnerDomainID, v))
}

// OwnerDomainIDIsNil applies the IsNil predicate on the "owner_domain_id" field.
func OwnerDomainIDIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldOwnerDomainID))
}

// OwnerDomainIDNotNil applies the NotNil predicate on the "owner_domain_id" field.
func OwnerDomainIDNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldOwnerDomainID))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldLabel, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldValue, v))
}

// ExtendEQ applies the EQ predicate on the "extend" field.
func ExtendEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldExtend, v))
}

// ExtendNEQ applies the NEQ predicate on the "extend" field.
func ExtendNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldExtend, v))
}

// ExtendIn applies the In predicate on the "extend" field.
func ExtendIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldExtend, vs...))
}

// ExtendNotIn applies the NotIn predicate on the "extend" field.
func ExtendNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldExtend, vs...))
}

// ExtendGT applies the GT predicate on the "extend" field.
func ExtendGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldExtend, v))
}

// ExtendGTE applies the GTE predicate on the "extend" field.
func ExtendGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldExtend, v))
}

// ExtendLT applies the LT predicate on the "extend" field.
func ExtendLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldExtend, v))
}

// ExtendLTE applies the LTE predicate on the "extend" field.
func ExtendLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldExtend, v))
}

// ExtendContains applies the Contains predicate on the "extend" field.
func ExtendContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldExtend, v))
}

// ExtendHasPrefix applies the HasPrefix predicate on the "extend" field.
func ExtendHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldExtend, v))
}

// ExtendHasSuffix applies the HasSuffix predicate on the "extend" field.
func ExtendHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldExtend, v))
}

// ExtendIsNil applies the IsNil predicate on the "extend" field.
func ExtendIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldExtend))
}

// ExtendNotNil applies the NotNil predicate on the "extend" field.
func ExtendNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldExtend))
}

// ExtendEqualFold applies the EqualFold predicate on the "extend" field.
func ExtendEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldExtend, v))
}

// ExtendContainsFold applies the ContainsFold predicate on the "extend" field.
func ExtendContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldExtend, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldSort, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v bool) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v bool) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldStatus, v))
}

// DictionaryIDEQ applies the EQ predicate on the "dictionary_id" field.
func DictionaryIDEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDictionaryID, v))
}

// DictionaryIDNEQ applies the NEQ predicate on the "dictionary_id" field.
func DictionaryIDNEQ(v uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldDictionaryID, v))
}

// DictionaryIDIn applies the In predicate on the "dictionary_id" field.
func DictionaryIDIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldDictionaryID, vs...))
}

// DictionaryIDNotIn applies the NotIn predicate on the "dictionary_id" field.
func DictionaryIDNotIn(vs ...uuid.UUID) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldDictionaryID, vs...))
}

// HasDictionary applies the HasEdge predicate on the "dictionary" edge.
func HasDictionary() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DictionaryTable, DictionaryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDictionaryWith applies the HasEdge predicate on the "dictionary" edge with a given conditions (other predicates).
func HasDictionaryWith(preds ...predicate.Dictionary) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(func(s *sql.Selector) {
		step := newDictionaryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.NotPredicates(p))
}
