// Code generated by ent, DO NOT EDIT.

package rolebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/leeforge/core/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldID, id))
}

// CreatedByID applies equality check predicate on the "created_by_id" field. It's identical to CreatedByIDEQ.
func CreatedByID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedByID applies equality check predicate on the "updated_by_id" field. It's identical to UpdatedByIDEQ.
func UpdatedByID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedByID applies equality check predicate on the "deleted_by_id" field. It's identical to DeletedByIDEQ.
func DeletedByID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldPublishedAt, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldArchivedAt, v))
}

// OwnerDomainID applies equality check predicate on the "owner_domain_id" field. It's identical to OwnerDomainIDEQ.
func OwnerDomainID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldOwnerDomainID, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldSubjectID, v))
}

// RoleCode applies equality check predicate on the "role_code" field. It's identical to RoleCodeEQ.
func RoleCode(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldRoleCode, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldProjectID, v))
}

// ScopeValue applies equality check predicate on the "scope_value" field. It's identical to ScopeValueEQ.
func ScopeValue(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldScopeValue, v))
}

// CreatedByIDEQ applies the EQ predicate on the "created_by_id" field.
func CreatedByIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedByIDNEQ applies the NEQ predicate on the "created_by_id" field.
func CreatedByIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldCreatedByID, v))
}

// CreatedByIDIn applies the In predicate on the "created_by_id" field.
func CreatedByIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldCreatedByID, vs...))
}

// CreatedByIDNotIn applies the NotIn predicate on the "created_by_id" field.
func CreatedByIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldCreatedByID, vs...))
}

// CreatedByIDGT applies the GT predicate on the "created_by_id" field.
func CreatedByIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldCreatedByID, v))
}

// CreatedByIDGTE applies the GTE predicate on the "created_by_id" field.
func CreatedByIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldCreatedByID, v))
}

// CreatedByIDLT applies the LT predicate on the "created_by_id" field.
func CreatedByIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldCreatedByID, v))
}

// CreatedByIDLTE applies the LTE predicate on the "created_by_id" field.
func CreatedByIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldCreatedByID, v))
}

// CreatedByIDIsNil applies the IsNil predicate on the "created_by_id" field.
func CreatedByIDIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldCreatedByID))
}

// CreatedByIDNotNil applies the NotNil predicate on the "created_by_id" field.
func CreatedByIDNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldCreatedByID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedByIDEQ applies the EQ predicate on the "updated_by_id" field.
func UpdatedByIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldUpdatedByID, v))
}

// UpdatedByIDNEQ applies the NEQ predicate on the "updated_by_id" field.
func UpdatedByIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldUpdatedByID, v))
}

// UpdatedByIDIn applies the In predicate on the "updated_by_id" field.
func UpdatedByIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDNotIn applies the NotIn predicate on the "updated_by_id" field.
func UpdatedByIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldUpdatedByID, vs...))
}

// UpdatedByIDGT applies the GT predicate on the "updated_by_id" field.
func UpdatedByIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldUpdatedByID, v))
}

// UpdatedByIDGTE applies the GTE predicate on the "updated_by_id" field.
func UpdatedByIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldUpdatedByID, v))
}

// UpdatedByIDLT applies the LT predicate on the "updated_by_id" field.
func UpdatedByIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldUpdatedByID, v))
}

// UpdatedByIDLTE applies the LTE predicate on the "updated_by_id" field.
func UpdatedByIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldUpdatedByID, v))
}

// UpdatedByIDIsNil applies the IsNil predicate on the "updated_by_id" field.
func UpdatedByIDIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldUpdatedByID))
}

// UpdatedByIDNotNil applies the NotNil predicate on the "updated_by_id" field.
func UpdatedByIDNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldUpdatedByID))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedByIDEQ applies the EQ predicate on the "deleted_by_id" field.
func DeletedByIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldDeletedByID, v))
}

// DeletedByIDNEQ applies the NEQ predicate on the "deleted_by_id" field.
func DeletedByIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldDeletedByID, v))
}

// DeletedByIDIn applies the In predicate on the "deleted_by_id" field.
func DeletedByIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldDeletedByID, vs...))
}

// DeletedByIDNotIn applies the NotIn predicate on the "deleted_by_id" field.
func DeletedByIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldDeletedByID, vs...))
}

// DeletedByIDGT applies the GT predicate on the "deleted_by_id" field.
func DeletedByIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldDeletedByID, v))
}

// DeletedByIDGTE applies the GTE predicate on the "deleted_by_id" field.
func DeletedByIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldDeletedByID, v))
}

// DeletedByIDLT applies the LT predicate on the "deleted_by_id" field.
func DeletedByIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldDeletedByID, v))
}

// DeletedByIDLTE applies the LTE predicate on the "deleted_by_id" field.
func DeletedByIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldDeletedByID, v))
}

// DeletedByIDIsNil applies the IsNil predicate on the "deleted_by_id" field.
func DeletedByIDIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldDeletedByID))
}

// DeletedByIDNotNil applies the NotNil predicate on the "deleted_by_id" field.
func DeletedByIDNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldDeletedByID))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldDeletedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldPublishedAt))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldArchivedAt))
}

// OwnerDomainIDEQ applies the EQ predicate on the "owner_domain_id" field.
func OwnerDomainIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldOwnerDomainID, v))
}

// OwnerDomainIDNEQ applies the NEQ predicate on the "owner_domain_id" field.
func OwnerDomainIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldOwnerDomainID, v))
}

// OwnerDomainIDIn applies the In predicate on the "owner_domain_id" field.
func OwnerDomainIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldOwnerDomainID, vs...))
}

// OwnerDomainIDNotIn applies the NotIn predicate on the "owner_domain_id" field.
func OwnerDomainIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldOwnerDomainID, vs...))
}

// OwnerDomainIDGT applies the GT predicate on the "owner_domain_id" field.
func OwnerDomainIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldOwnerDomainID, v))
}

// OwnerDomainIDGTE applies the GTE predicate on the "owner_domain_id" field.
func OwnerDomainIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldOwnerDomainID, v))
}

// OwnerDomainIDLT applies the LT predicate on the "owner_domain_id" field.
func OwnerDomainIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldOwnerDomainID, v))
}

// OwnerDomainIDLTE applies the LTE predicate on the "owner_domain_id" field.
func OwnerDomainIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldOwnerDomainID, v))
}

// OwnerDomainIDIsNil applies the IsNil predicate on the "owner_domain_id" field.
func OwnerDomainIDIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldOwnerDomainID))
}

// OwnerDomainIDNotNil applies the NotNil predicate on the "owner_domain_id" field.
func OwnerDomainIDNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldOwnerDomainID))
}

// SubjectTypeEQ applies the EQ predicate on the "subject_type" field.
func SubjectTypeEQ(v SubjectType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectTypeNEQ applies the NEQ predicate on the "subject_type" field.
func SubjectTypeNEQ(v SubjectType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldSubjectType, v))
}

// SubjectTypeIn applies the In predicate on the "subject_type" field.
func SubjectTypeIn(vs ...SubjectType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldSubjectType, vs...))
}

// SubjectTypeNotIn applies the NotIn predicate on the "subject_type" field.
func SubjectTypeNotIn(vs ...SubjectType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldSubjectType, vs...))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldSubjectID, v))
}

// RoleCodeEQ applies the EQ predicate on the "role_code" field.
func RoleCodeEQ(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldRoleCode, v))
}

// RoleCodeNEQ applies the NEQ predicate on the "role_code" field.
func RoleCodeNEQ(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldRoleCode, v))
}

// RoleCodeIn applies the In predicate on the "role_code" field.
func RoleCodeIn(vs ...string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldRoleCode, vs...))
}

// RoleCodeNotIn applies the NotIn predicate on the "role_code" field.
func RoleCodeNotIn(vs ...string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldRoleCode, vs...))
}

// RoleCodeGT applies the GT predicate on the "role_code" field.
func RoleCodeGT(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldRoleCode, v))
}

// RoleCodeGTE applies the GTE predicate on the "role_code" field.
func RoleCodeGTE(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldRoleCode, v))
}

// RoleCodeLT applies the LT predicate on the "role_code" field.
func RoleCodeLT(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldRoleCode, v))
}

// RoleCodeLTE applies the LTE predicate on the "role_code" field.
func RoleCodeLTE(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldRoleCode, v))
}

// RoleCodeContains applies the Contains predicate on the "role_code" field.
func RoleCodeContains(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldContains(FieldRoleCode, v))
}

// RoleCodeHasPrefix applies the HasPrefix predicate on the "role_code" field.
func RoleCodeHasPrefix(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldHasPrefix(FieldRoleCode, v))
}

// RoleCodeHasSuffix applies the HasSuffix predicate on the "role_code" field.
func RoleCodeHasSuffix(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldHasSuffix(FieldRoleCode, v))
}

// RoleCodeEqualFold applies the EqualFold predicate on the "role_code" field.
func RoleCodeEqualFold(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEqualFold(FieldRoleCode, v))
}

// RoleCodeContainsFold applies the ContainsFold predicate on the "role_code" field.
func RoleCodeContainsFold(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldContainsFold(FieldRoleCode, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldProjectID))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v ScopeType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v ScopeType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...ScopeType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...ScopeType) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeValueEQ applies the EQ predicate on the "scope_value" field.
func ScopeValueEQ(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldScopeValue, v))
}

// ScopeValueNEQ applies the NEQ predicate on the "scope_value" field.
func ScopeValueNEQ(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldScopeValue, v))
}

// ScopeValueIn applies the In predicate on the "scope_value" field.
func ScopeValueIn(vs ...string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldScopeValue, vs...))
}

// ScopeValueNotIn applies the NotIn predicate on the "scope_value" field.
func ScopeValueNotIn(vs ...string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldScopeValue, vs...))
}

// ScopeValueGT applies the GT predicate on the "scope_value" field.
func ScopeValueGT(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGT(FieldScopeValue, v))
}

// ScopeValueGTE applies the GTE predicate on the "scope_value" field.
func ScopeValueGTE(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldGTE(FieldScopeValue, v))
}

// ScopeValueLT applies the LT predicate on the "scope_value" field.
func ScopeValueLT(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLT(FieldScopeValue, v))
}

// ScopeValueLTE applies the LTE predicate on the "scope_value" field.
func ScopeValueLTE(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldLTE(FieldScopeValue, v))
}

// ScopeValueContains applies the Contains predicate on the "scope_value" field.
func ScopeValueContains(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldContains(FieldScopeValue, v))
}

// ScopeValueHasPrefix applies the HasPrefix predicate on the "scope_value" field.
func ScopeValueHasPrefix(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldHasPrefix(FieldScopeValue, v))
}

// ScopeValueHasSuffix applies the HasSuffix predicate on the "scope_value" field.
func ScopeValueHasSuffix(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldHasSuffix(FieldScopeValue, v))
}

// ScopeValueIsNil applies the IsNil predicate on the "scope_value" field.
func ScopeValueIsNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIsNull(FieldScopeValue))
}

// ScopeValueNotNil applies the NotNil predicate on the "scope_value" field.
func ScopeValueNotNil() predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotNull(FieldScopeValue))
}

// ScopeValueEqualFold applies the EqualFold predicate on the "scope_value" field.
func ScopeValueEqualFold(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEqualFold(FieldScopeValue, v))
}

// ScopeValueContainsFold applies the ContainsFold predicate on the "scope_value" field.
func ScopeValueContainsFold(v string) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldContainsFold(FieldScopeValue, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RoleBinding {
	return predicate.RoleBinding(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoleBinding) predicate.RoleBinding {
	return predicate.RoleBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoleBinding) predicate.RoleBinding {
	return predicate.RoleBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleBinding) predicate.RoleBinding {
	return predicate.RoleBinding(sql.NotPredicates(p))
}
